# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser.
# https://goreleaser.com

class Listcoder < Formula
  desc "AI-powered development tool"
  homepage "https://github.com/legitey01/List-Coder-CLI-Realeses"
  version "0.1.4"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/legitey01/List-Coder-CLI-Realeses/releases/download/v#{version}/listcoder-x86_64-apple-darwin"
      sha256 "PLACEHOLDER_SHA256_MACOS_X86_64"
    end
    on_arm do
      url "https://github.com/legitey01/List-Coder-CLI-Realeses/releases/download/v#{version}/listcoder-aarch64-apple-darwin"
      sha256 "PLACEHOLDER_SHA256_MACOS_ARM64"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/legitey01/List-Coder-CLI-Realeses/releases/download/v#{version}/listcoder-x86_64-unknown-linux-gnu"
      sha256 "PLACEHOLDER_SHA256_LINUX_X86_64"
    end
    on_arm do
      url "https://github.com/legitey01/List-Coder-CLI-Realeses/releases/download/v#{version}/listcoder-aarch64-unknown-linux-gnu"
      sha256 "PLACEHOLDER_SHA256_LINUX_ARM64"
    end
  end

  def install
    bin.install "listcoder"
  end

  test do
    system "#{bin}/listcoder", "--version"
  end
end
